version: '3'

services:

##################################
#   Setup node container
##################################
  server:
    build: ./backend
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    # volumes:
    #   - ./backend/src:srv/app/fullstack-app-server/src
    command: npm run start


###################################
#   Setup client container
###################################
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    # volumes:
    #   - ./client/src:srv/app/fullstack-app-client/src
    #   - ./client/public:srv/app/fullstack-app-client/public
    command: npm run start
